- name: Update system
  hosts: all
  tasks:
    - name: Update goodies
      become: true
      become_user: root
      ansible.builtin.dnf:
        pkg:
          - "*"
        update_only: true
        state: latest
